### ISSUE TITLE
1주차 - 프로젝트 시작

### ISSUE THREAD

**Issue by shongs27** [CodeSoom/project-react-6-shongs27#1]
### 1. 이 앱을 언제 사용하나요?

개인 기술 블로그로 직접 운영하는 목적으로 만듭니다

### 2. 구체적인 사례는 무엇인가요?

관리자는,
관리자 계정으로 로그인을 할 수 있고
블로그의 글을 CRUD할 수 있으며
최근포스트와 인기포스트를 확인할 수 있고
전체 방문자를 확인할 수 있으며
검색 기능을 통해 블로그 포스팅을 찾을 수 있으며
재밌는 기능을 몇 가지를 추가합니다 (ex 웹게임)

방문자는,
이메일 혹은 게시판을 통해 글을 쓸 수 있으며
포스팅을 보고 검색할 수 있으며 
재밌는 기능을 사용할 수 있습니다  (ex 웹게임)

### 3. 이번주가 지나면 사용자는 무엇을 할 수 있나요?

전체적인 UI를 확인 할 수 있습니다

### 4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

- 개발환경 직접 세팅
- 블로그 UI 조사 및 계획
- 전체적인 구조 작성
- 헤더부분 작성

![블로그 UI 계획](https://user-images.githubusercontent.com/55541745/151574306-61ca63a7-7f02-43b6-a359-c5134cac5764.png)

**Comment by moonkii** [comment]
![image](https://user-images.githubusercontent.com/46776329/151569473-d61fe5ea-7bda-4338-95a2-986347834d50.png)

애플리케이션에서 가장 핵심이 되는 기능은 무엇인가요?
최소한 어떤 기능을 포함해야 사람들이 블로그라는 걸 알 수 있을까요?

예를들어 쇼핑몰로 설명을 해볼게요.
사람들에게 쇼핑몰을 개발하라고 하면 가장 먼저 로그인부터 만들려는 시도를 많이해요.
쇼핑몰의 본질은 무엇일까요? 저는 물건을 팔 수 있게 하는 것이라고 생각해요.
당장 하루밖에 시간이 없다면 쇼핑몰을 어떻게 만들 수 있을까요?
만약에 저라면 제품을 소개할 수 있는 페이지만 하나 만들어서 사람들에게 보여줄 것 같아요.
극단적으로 상품은 하드코딩하고 결제는 계좌이체로라도 받을 수 있을거에요.

앞으로 개인 프로젝트는 1주차씩 끊어서 진행하신다고 생각하시면 좋아요. 당장 1주일만에 제품을 만들어서 배포해야한다면
어떤 것부터 만들면 좋을까요?
처음부터 완벽한 앱을 설계해서 만드는 건 힘들어요.
그렇기 때문에 어설프게 전체를 만드는 것 보다 강력한 하나의 핵심 기능을 만들어서 사람들에게 보여주는게 더 좋을거에요.
그리고 매주 사람들의 피드백까지 받을 수 있으면 더욱 좋을거에요. 실제 사용자의 피드백을 받아 조금씩 개선해 나가는 구조죠.
매주 이러한 사이클로 작동한 기능을 채워나가고 완성해나가면 소위 우리가 말하는 “애자일” 하게 개발이 가능할거에요.

**Comment by shongs27** [comment]
블로그의 핵심은 글을 읽고 쓰는 것에 있는데요,
선택과 집중을 하라는 말씀으로 이해했습니다

매주 양질의 피드백을 받을 수 있도록 노력할께요
