### ISSUE TITLE
글 렌더링을 위한 설계 재고

### ISSUE THREAD

**Issue by shongs27** [CodeSoom/project-react-6-shongs27#5]
글을 db에서 보관하기 위해 json-server를 사용했는데

정적사이트 배포를 위해 백엔드 서버를 구축하는 것이 아니라 

vs코드로 블로거글을 작성하고 해당 항목을 깃의 포스팅으로 배포하게 변경

**Comment by ahastudio** [comment]
프로덕트 레벨로 바로 가는군요! 👍

**Comment by shongs27** [comment]
json server에서 실제 백엔드 서버로 구현으로 변경

**Comment by shongs27** [comment]
ㅂㄷㄹ
